=begin
#Draft Orders API

#Shopify Draft Orders API

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instact of DefaultApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DefaultApi)
    end
  end

  # unit tests for admin_draft_orders_count_json_get
  # Return count
  # Returns count of draft orders
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'admin_draft_orders_count_json_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_orders_json_get
  # Gets draft orders test test test
  # Retrieve a list of all Draft Orders please !!!! and thank you
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields Comma-separated list of fields to include in the response
  # @option opts [Integer] :limit Page size
  # @option opts [Integer] :page Page to show
  # @return [DraftOrder]
  describe 'admin_draft_orders_json_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_orders_json_post
  # Creates a draft order
  # send a draft order in body of the request
  # @param draftorder The draft order to create.
  # @param [Hash] opts the optional parameters
  # @return [DraftOrder]
  describe 'admin_draft_orders_json_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_ordersid_checkout_json_post
  # Create or retrieve existing checkout for this draft order, to be used in Checkout API. Requires checkout scope
  # 
  # @param id2 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id id of the draft order
  # @return [Checkout]
  describe 'admin_draft_ordersid_checkout_json_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_ordersid_complete_json_put
  # Remove a Draft Order from the database
  # 
  # @param id2 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id id of the draft order
  # @option opts [Integer] :payment_gateway_id Gateway used to receive payment. Either ID of custom manual gateway, or null if using the default “Mark As Paid” gateway.
  # @option opts [BOOLEAN] :payment_pending true/false
  # @return [DraftOrder]
  describe 'admin_draft_ordersid_complete_json_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_ordersid_json_delete
  # removes a draft order from the database.
  # retruns {}
  # @param id draft order id
  # @param [Hash] opts the optional parameters
  # @return [DraftOrder]
  describe 'admin_draft_ordersid_json_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_ordersid_json_get
  # Receive a single Draft Order
  # Receive a single Draft Order
  # @param id draft order id
  # @param [Hash] opts the optional parameters
  # @return [DraftOrder]
  describe 'admin_draft_ordersid_json_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_ordersid_json_put
  # Modify an existing draft order
  # Modify an existing draft order. ### Example   Only showing the parameters needed to select a particular shipping rate as returned from     &#x60;GET /admin/draft_orders/#{id}/shipping_rates&#x60;       draft_order: {       shipping_line: {         handle: ,         phone:       }     }     
  # @param id draft order id
  # @param [Hash] opts the optional parameters
  # @option opts [DraftOrder] :draft_order the draft order to modify.
  # @return [DraftOrder]
  describe 'admin_draft_ordersid_json_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_ordersid_send_invoice_json_post
  # Send Invoice - “Minimal request” does not require any parameters to be sent (no request body at all or just an empty draft_order_invoice hash)
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [DraftOrderInvoice] :draft_order_invoice draft_order_invoice to post.
  # @return [DraftOrderInvoice]
  describe 'admin_draft_ordersid_send_invoice_json_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for admin_draft_ordersid_shipping_rates_json_get
  # gets shipping rates for a specific draft order
  # Get a list of available shipping rates for the specified draft order. Implementers will need to poll this endpoint until rates become available. Calling this endpoint without first specifying a shipping address on the draft order will return an error response. Possible responses outlined below.    #### Rates have been requested and are available   &#x60;&#x60;&#x60;    # Response HTTP/1.1 200 OK {   \&quot;shipping_rates\&quot;: [     {       \&quot;handle\&quot;: \&quot;shopify-Standard%20Shipping-10.00\&quot;,       “phone_required”: false,       \&quot;price\&quot;: \&quot;10.00\&quot;,       \&quot;title\&quot;: \&quot;Standard Shipping\&quot;,       “draft_order”:        {          “subtotal_price”: “10.00”,          “total_price”: “21.50”,          “total_tax”: “1.50”       }     },     {       \&quot;handle\&quot;: \&quot;ups-11-19.45\&quot;,       “phone_required”: false,       \&quot;price\&quot;: \&quot;19.45\&quot;,       \&quot;title\&quot;: \&quot;UPS Standard\&quot;,       “draft_order”:        {          “subtotal_price”: “10.00”,          “total_price”: “30.95”,          “total_tax”: “1.50”       }     },     {       \&quot;handle\&quot;: \&quot;ups-02-19.69\&quot;,       “phone_required”: true,       \&quot;price\&quot;: \&quot;19.69\&quot;,       \&quot;title\&quot;: \&quot;UPS Expedited\&quot;,       “draft_order”:        {          “subtotal_price”: “10.00”,          “total_price”: “31.19”,          “total_tax”: “1.50”       }     }   ] }        &#x60;&#x60;&#x60;   #### Rates have been requested but none are available for the current shipping address      # Response     HTTP/1.1 200 OK     {       \&quot;shipping_rates\&quot;: []     } 
  # @param id2 draft order id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id id of the draft order
  # @return [ShippingRate]
  describe 'admin_draft_ordersid_shipping_rates_json_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
